name: Build CoreDNS

on:
 workflow_dispatch:
#  schedule:
#    - cron: '0 0 1 * *'
   
jobs:
  build-coredns:
    name: Build on macos
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'coredns/coredns'
      
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      
      - name: Append custom plugins
        run: echo 'alternate:github.com/coredns/alternate' >> plugin.cfg
        
      - name: Build
        run: make SYSTEM="GOOS=darwin GOARCH=arm64"
       
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coredns
          path: coredns
